export enum StatusCodeEnums {
    OK = 'OK',
    UNEXPECTED = 'UNEXPECTED',
    UNPROCESSABLE_ENTITY = 'UNPROCESSABLE ENTITY',
    INVALID_CREDENTIALS = 'INVALID CREDENTIALS',
    INCORRECT_PASSWORD = 'INCORRECT PASSWORD',
}
